### ISSUE TITLE
OBS container build on Dockerfile parses zypper parameter incorrectly

### ISSUE THREAD

**Issue by okurz** [openSUSE/open-build-service#10396]
Issue
=====

Trying to build a container using a Dockerfile that is valid for use of docker build fails due to zypper parameters being parsed incorrectly. In https://build.opensuse.org/package/show/home:okurz:container/openQA_from_git_Dockerfile the project can be seen with a Dockerfile of similar content to:

```
FROM opensuse/leap:15.2
RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/openSUSE_Leap_15.2 devel_openQA && \
    zypper ar -p 90 -f http://download.opensuse.org/repositories/devel:openQA:Leap:15.2/openSUSE_Leap_15.2 devel_openQA_Leap
RUN zypper --gpg-auto-import-keys ref
…
```

which fails with `broken: cannot map '90' to obs` due to the zypper call with parameter `zypper ar -p 90` incorrectly parsed.

Expected Result
============
Either the parameter `-p 90` should be ignored or valued with proper repository priorities during building or a clear error feedback to the user should be provided what is supported within OBS and what not.

How to Reproduce
===============
1. Create container package with Dockerfile
2. Add a line to Dockerfile like `RUN zypper ar -p 90 http://download.opensuse.org/tumbleweed/repo/oss/`
3. Observe the build failing due to the parameter `-p 90`

Further Information
===============
My motivation is to build containers based on a correct, usable Dockerfile using OBS not needing to create OBS specific files nor relying on hub.docker.com

**Comment by adrianschroeter** [comment]
On Donnerstag, 5. November 2020, 20:17:30 CET Oliver Kurz wrote:
> Issue
> =====
> 
> Trying to build a container using a Dockerfile that is valid for use of docker build fails due to zypper parameters being parsed incorrectly. In https://build.opensuse.org/package/show/home:okurz:container/openQA_from_git_Dockerfile the project can be seen with a Dockerfile of similar content to:
> 
> ```
> FROM opensuse/leap:15.2
> RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/openSUSE_Leap_15.2 devel_openQA && \
>     zypper ar -p 90 -f http://download.opensuse.org/repositories/devel:openQA:Leap:15.2/openSUSE_Leap_15.2 devel_openQA_Leap
> RUN zypper --gpg-auto-import-keys ref
> …
> ```
> 
> which fails with `broken: cannot map '90' to obs` due to the zypper call with parameter `zypper ar -p 90` incorrectly parsed.
> 
> Expected Result
> ============
> Either the parameter `-p 90` should be ignored or valued with proper repository priorities during building or a clear error feedback to the user should be provided what is supported within OBS and what not.

not sure if either of it makes sense.

When ignoring it the result will be different.

supporting it can not work always, since repository definition can also come from project meta. You do not
have priorities, but orders there.

So, my initial thought would be that we do not support this parameter rightfully. We
could improve the error message though...

Michael, what is your take on this?

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by mlschroe** [comment]
Fixed in https://github.com/openSUSE/obs-build/commit/ae8c1ce6f550901584274ef53581e71099d4c56a
(already deployed)

**Comment by okurz** [comment]
Wow, this was quick. Thank you! I can confirm https://build.opensuse.org/package/show/home:okurz:container/openQA_from_git_Dockerfile looks better now although I don't know why it's now "unresolvable: nothing provides container:opensuse/leap:15.2"

**Comment by okurz** [comment]
Oh, also it looks like "containers_arm aarch64" is still broken with "broken: cannot map '90' to obs"
