### ISSUE TITLE
obs-2.6: After logging in you are redirected to wrong url

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1138]
In commit b7307c2beaa7dbf4e77d063ef65e12dcbe74272e, redirect logic was changed after login. In 2.6.4, it sometimes makes you go wrong url, such as profile image, build log, rpmlint file etc, instead of the actual page you were at.

Steps to reproduce in fresh OBS 2.6.4 ISO image:
1) Sign up a new user
2) Create home project
3) Log out, get redirected to front page
4) Go to home project
5) Login
6) Get redirected to some url other than the page you were at, like non-existing build result page

**Comment by bgeuken** [comment]
This should get fixed with the next 2.6 release by PR#1386

**Comment by jsjhb** [comment]
I am sorry to report this issue not fixed. In current obs 2.6.7 built Dec 9 redirects after login are still routed to arbitrary local URLs.
