### ISSUE TITLE
All AJAX functionalities in WebUI are broken with IE11

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1622]
With IE11, all AJAX related functionality is broken.

For example:
In 2.6, project level (right-hand) repository statuses won't load (uses AJAX).
In master (build.opensuse.org), the main project list do not load, nor does status monitor infos, or package build logs...

**Comment by NickLion** [comment]
This isn't IE11 problem. File
/assets/webui/application-bb704bf16e3d550eeedda7db96f2fc71e9e70c62aca0eaf79f1a11e0d5fbbc0e.js
returns 404 and as result "$" (jQuery?) doesn't work.

**Comment by adrianschroeter** [comment]
I suppose it is solved now.

(lacking restart of broken passenger package for SLE11 :/)

**Comment by tuminoid** [comment]
OK, that explains the issue build.opensuse.org.

This is still an issue in our 2.6 based OBS. It works perfectly with other browsers, but not IE11, so it is not about missing jQuery. 8b0baa0c623f9f0b73d071a855938bfeb4c1dde6 updated jquery-rails in February, could that cause IE incompatibility?
