### ISSUE TITLE
WebUI Download logfile does not do anything

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1629]
If you are in the logfile in the WebUI and click on Download logfile you still stay in the partial logfile. E.g. <baseurl>/package/live_build_log/<project>/<package>/<repo>/<arch> shows the same as  the Download logfile link.

**Comment by mmohring** [comment]
That is on the build.o.o instance WebUI.

**Comment by mmohring** [comment]
It seems not to happen on my local OBS, which uses git commit e3ef2391894737cd7b15d3f3e16b01c1aaf23666 for the code of obs-server.

**Comment by mmohring** [comment]
My Webbrowser is Firefox 45.0 on openSUSE.

**Comment by ChrisBr** [comment]
duplicate of #1603, closing ...
Thanks for reporting anyway!

**Comment by ChrisBr** [comment]
@mmohring you state that it works for you with e3ef239, however, this commit is only 6 days old and @adrianschroeter already reported this issue 11 days ago... weird!

**Comment by mmohring** [comment]
@ChrisBr so you say this is fixed but code not deployed in build.o.o ? "osc api about" on api.opensuse.org shows version 2.6.51.git20160309.e3ef239 . I intentionally used the same on my local instance. I guess some configuration issue, for example the use of frontend_host / external_frontend_host in config/options.yml .

**Comment by ChrisBr** [comment]
No, it's not fixed atm but we have already an open issue for it, so just closed the duplicate ...

**Comment by ChrisBr** [comment]
@adrianschroeter When I click "Download logfile" it redirects me to this page:

![logs_obs](https://cloud.githubusercontent.com/assets/3799140/13828742/c6110c70-eb88-11e5-9dae-d05006b48938.png)

I thought this is expected? How is it supposed to work?

Furthermore, the only change on the download link was 45ba8e9aa39d41ebaac0b42f92bd0c7efce23c25 which produces the exact same url (I tried it)! So currently I'm not able to reproduce ...

**Comment by coolo** [comment]
this redirected page only does something meaningful if you're logged in - for anonymous you're just redirected back. So either rawlog needs to be accessible for anonymous or you remove the download logfile link for anonymous

**Comment by adrianschroeter** [comment]
We do not want to remove access for anonymous (if anonymous access is enabled explicit). So it is fine to open this specific route. Or better point to the /public route in anonymous case. This should have the check for anonymous configuration already.
