### ISSUE TITLE
Overlapping html label element prevents from selecting adjacent image template

### ISSUE THREAD

**Issue by binary-sequence** [openSUSE/open-build-service#16428]
# Issue Description
On https://build.opensuse.org/image_templates
When "Application Container using Dockerfile" is selected
And I try to select "openSUSE Tumbleweed Minimal Images"
Then it doesn't get selected, because the html label of the adjacent image template overlaps the radio button.

Expected Result
============
On https://build.opensuse.org/image_templates
When "Application Container using Dockerfile" is selected
And I try to select "openSUSE Tumbleweed Minimal Images"
Then it gets selected.

Screenshot
=========
<img width="1456" alt="obs-image-templates-overlapping-label" src="https://github.com/openSUSE/open-build-service/assets/2727538/d7892c3a-ce04-401e-8fe4-1f36d1f1a6e1">

**Comment by ncounter** [comment]
Would you mind to tell us about the device and browser version you're using? It may be a corner case to handle properly,  as it works well on the most common and tested scenarios instead.
Thank you for reporting it.

**Comment by binary-sequence** [comment]
I can reproduce it on all my machines
- openSUSE Tumbleweed (Chrome, Firefox)
- MacOS (Safari, Chrome, Firefox)

Since you mentioned that it works on all common and tested scenarios, I have tried on another monitor, I it looked good. So, I thought it could be a different window size (caused by different resolution screen). And I can now reproduce it on the other screen when I resize the window smaller.

Screen recording on Tumbleweed with Chrome (I couldn't get the cursor recorded...)
https://github.com/openSUSE/open-build-service/assets/2727538/5fbe2b65-5bdc-490c-b2d5-6c0b9f67e561

**Comment by binary-sequence** [comment]
Any update here?
I think I didn't describe the problem properly.

The responsive design is not working, on any device, on any browser, since the boxes overlaps each other between screen size steps.
For example, starting at **windows.innerWidth of 768**, the boxes overlap until **windows.innerWidth of 795**, and so on.
The problem is even more noticeable **from 992 to 1490**.

I encountered the problem because my screen width resolution at home is between 992 and 1490. Any device and browser using a screen width resolution between those ranges will encounter the problem.

**Comment by rajyashhh** [comment]
Is this issue fixed now? If not, I am ready to fix this one.

**Comment by ncounter** [comment]
> Is this issue fixed now? If not, I am ready to fix this one.

Hi @rajyashhh . I believe the issue is still valid, yes.
Of course any contribution would be much appreciated 😃 

JFYI we have a [contribution guideline](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-contribute-code) in case you plan to implement the fix and open a PR.

And we are also here to collaborate as well 😉

**Comment by hema-hema123** [comment]
Hi @ncounter, thanks for confirming!
I can reproduce this on Chrome when resizing the window to smaller widths.
I’d like to work on fixing the responsive layout / overlap issue and open a PR.

**Comment by ncounter** [comment]
> Hi [@ncounter](https://github.com/ncounter), thanks for confirming! I can reproduce this on Chrome when resizing the window to smaller widths. I’d like to work on fixing the responsive layout / overlap issue and open a PR.

That is cool @hema-hema123 

Make sure to follow our [contribution guideline](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-contribute-code) while tackling it.

We're here to collaborate in case you will.
And don't forget to have fun 🙂

**Comment by hema-hema123** [comment]
Thanks a lot! 😊
I’ll follow the contribution guidelines while working on it.
I’ve started looking into the responsive layout issue and will reach out here if I need any clarification.

**Comment by Dotify71** [comment]
I have just made a pr for this issue as this issue and the other pr is left abandoned for the past 6 months. So you can have a look at my pr at https://github.com/openSUSE/open-build-service/pull/19931
