### ISSUE TITLE
"Package has no source revision yet"

### ISSUE THREAD

**Issue by rifux** [openSUSE/open-build-service#17250]
# Issue Description

I'm encountering an error message "Package has no source revision yet" when attempting to create a new kiwi image using the OBS web interface.

Expected Result
============

The process should result in a fully functional kiwi repository.

Observed Behavior:
===============

Instead of creating the repository, an error message appears stating "Package has no source revision yet."

![image](https://github.com/user-attachments/assets/94b6407d-e810-4ba5-9607-78010774329a)

How to Reproduce
===============

1. Access the OBS web UI at [https://build.opensuse.org](https://build.opensuse.org) and log in.
2. Follow this link: [https://build.opensuse.org/image_templates](https://build.opensuse.org/image_templates) (can be accessed via [https://studioexpress.opensuse.org](https://studioexpress.opensuse.org))
3. Choose "openSUSE Tumbleweed Minimal Images" and then click "Create appliance."

Additional information
===============

* This issue appears to be recurring: https://github.com/openSUSE/open-build-service/issues/15452

**Comment by hellcp-work** [comment]
This is for the same reason as before, there is an issue with the template image package, we should detect if that's the case and hide them from options that can be selected

**Comment by rifux** [comment]
> and hide them from options that can be selected

And how do we create openSUSE TW - based images then?

**Comment by hellcp-work** [comment]
Well, somebody would still have to come in and fix the issue with the source package, but we would avoid allowing people to reach this error

**Comment by adrianschroeter** [comment]
nah, please don't hide it. If the setup got messed up, we need to see and fix it...

**Comment by adrianschroeter** [comment]
I merged the conflicting change now. Should work again.

**Comment by hellcp-work** [comment]
> nah, please don't hide it. If the setup got messed up, we need to see and fix it...

We should still do something, notify maintainers and make sure that the users can't select an option that ends up with an error seems like the best solution

**Comment by rifux** [comment]
if selecting [openSUSE Tumbleweed Minimal Images](https://build.opensuse.org/package/show/openSUSE:Templates:Images:Tumbleweed/kiwi-templates-Minimal) the error persists:

![Image](https://github.com/user-attachments/assets/8913b9e5-3add-4c63-b99b-df526dad3381)

with [openSUSE Leap Micro 6.0 Images](https://build.opensuse.org/package/show/openSUSE:Templates:Images:Leap-Micro-6.0/Leap-Micro) selected I have this error:

![Image](https://github.com/user-attachments/assets/a9fcea9d-5527-449e-ad3c-49d267788ccc)

**Comment by rifux** [comment]
> make sure that the users can't select an option that ends up with an error seems like the best solution

I think the best solution is to fix the error itself, not to remove an option entirely ;)

**Comment by hellcp-work** [comment]
Considering that resolving conflicts requires a human intervention, that's easier said than done

**Comment by DAK404** [comment]
I am still facing this issue. I am unable to select an appliance and work on it. Is there a guide on what I can do for the moment to mitigate it or work around it?

Thanks!

Edit: Added screenshot

<img width="1562" height="827" alt="Image" src="https://github.com/user-attachments/assets/6d48326c-ffba-4817-b2ed-045f9323258d" />
