### ISSUE TITLE
webui: default to showing openSUSE_Tumbleweed rpmlint log

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#3183]
Observed result
===============
Open the SR https://build.opensuse.org/request/show/498603 in the web interface and then switch from "Build Results" to "Rpmlint Results". standard.i586 will be preselected. However, as the package is not built for i586, there is no rpmlint log to show.

Expected result
================
For the sake of opensuse-review-team, this should instead default to a project/arch which
1. has `<path project="openSUSE:Factory">` or Tumbleweed somewhere in the chain
2. actually has an rpmlint log file

**Comment by ChrisBr** [comment]
@adrianschroeter @jengelh 
does it make sense to drop the ``excluded`` architectures combinations in ``rpmlint_result``

https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L930

BuildResult looks like this
```
{"state"=>"42",
 "result"=>
  [{"project"=>"devel:openSUSE:Factory",
    "repository"=>"standard",
    "arch"=>"x86_64",
    "code"=>"published",
    "state"=>"published",
    "status"=>{"package"=>"opera", "code"=>"succeeded"}},
   {"project"=>"devel:openSUSE:Factory",
    "repository"=>"standard",
    "arch"=>"i586",
    "code"=>"published",
    "state"=>"published",
    "status"=>{"package"=>"opera", "code"=>"excluded"}}]}
```
so that would be an obvious easy step...

Another easy solution is to iterate over the combinations till we get an rpmlint result.

**Comment by adrianschroeter** [comment]
On Donnerstag, 10. August 2017, 18:20:08 CEST wrote Christian Bruckmayer:
> @adrianschroeter @jengelh 
> does it make sense to drop the ``excluded`` architectures combinations in ``rpmlint_result``

excluded ones should have no build results no rpmlint files actually ...

> 
> https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L930
> 
> BuildResult looks like this
> ```
> {"state"=>"42",
>  "result"=>
>   [{"project"=>"devel:openSUSE:Factory",
>     "repository"=>"standard",
>     "arch"=>"x86_64",
>     "code"=>"published",
>     "state"=>"published",
>     "status"=>{"package"=>"opera", "code"=>"succeeded"}},
>    {"project"=>"devel:openSUSE:Factory",
>     "repository"=>"standard",
>     "arch"=>"i586",
>     "code"=>"published",
>     "state"=>"published",
>     "status"=>{"package"=>"opera", "code"=>"excluded"}}]}
> ```
> so that would be an obvious easy step...
> 
> Another easy solution is to iterate over the combinations till we get an rpmlint result.
> 
> 


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by ChrisBr** [comment]
@adrianschroeter so we can safely drop them from the dropdown, right?

**Comment by adrianschroeter** [comment]
I think so

**Comment by ChrisBr** [comment]
But way more complex as it would mean that we need to iterate over all repo / arch combinations. This is implemented with AJAX atm so this approach would make it a lot more complicated. So if there does anyway no rpmlint result exist if this combination is excluded, why doing it the hard way?

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Drop excluded repository architecture combination from rpmlint dropdown #3608](https://trello.com/c/6qYl1JfM/496-drop-excluded-repository-architecture-combination-from-rpmlint-dropdown-3608)

**Comment by bgeuken** [comment]
Fixed and deployed to build.opensuse.org.

=> closing

**Comment by ChrisBr** [comment]
@bgeuken it is not fixed, the PR is one way to tackle the problem but not everything
