### ISSUE TITLE
webui may not show any hint that a package is a link/branch

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#4916]
Issue/Feature description
====================

webui is not showing package link information (links to on top right of package show page), if target is not existing target project.

This is the case when the package is not available at all or only available indirectly. This is the case for every branch from a stable distribution as long as no maintenance update has been shipped and therefore relative grave (Links to :Update, but source exists only via project link).

Expected result
============

We should always show the link information if it is defined in the source.

We may not want to make it a link if the target does not exist direct.

We may want to show additional information if target is not reachable at all.

How to Reproduce
===============
Branch any package from a stable distro where no maintenance update has been released. eg.  openSUSE:Leap:42.3:Update hello

Further information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by vpereira** [comment]
related with #673

**Comment by adrianschroeter** [comment]
@vpereira so this issue is fixed and we can close the issue?

**Comment by adrianschroeter** [comment]
yes, verified.

**Comment by frispete** [comment]
Something is still broken in my instance, that I updated right now to 2.9.5:

![grafik](https://user-images.githubusercontent.com/1009685/49235679-e8541c00-f3fa-11e8-8472-0713f45c0d97.png)

but unexpanded co:
![grafik](https://user-images.githubusercontent.com/1009685/49235781-1cc7d800-f3fb-11e8-9b6a-439a4f3ee305.png)

Any idea, what could be wrong here?

**Comment by frispete** [comment]
Hmm, the commits reference changes in June, therefore I hoped to catch them in the latest OBS for production use. See description of: https://build.opensuse.org/project/show/OBS:Server:Unstable
