### ISSUE TITLE
[mobile] Diff view jumping buttons and View file wrongly rendered

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#5987]
# Issue Description
In bootstrap mode when viewing the revisions diff of a package in a mobile (Xiaomi Mi 5S Plus) the buttons of View file disappear and the ^up and down buttons overlay the text in some cases.

![image](https://user-images.githubusercontent.com/11314634/46338514-ab54ee80-c630-11e8-9b17-e6182b5b6f75.png)

Expected Result
============
To have the buttons not overlaying any other element and that the View file buttons are properly rendered.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/rdiff/home:suse-cloud-ci:rpm-packaging-sles12-Master-04a052570e9c74eda72d86ad2726e42809a8f7c0/openstack-monasca-api?linkrev=base&rev=2 on a mobile device
2. See the misplaced buttons and how View file buttons aren't properly rendered

**Comment by ChrisBr** [comment]
The `View file` link issue is fixed and merged. @DavidKang any good idea how we can fix the button overlapping with the summary?

**Comment by mdeniz** [comment]
Still failing in some size

![image](https://user-images.githubusercontent.com/11314634/46464825-9199df80-c7c7-11e8-9602-76d056fa19d3.png)
