### ISSUE TITLE
Add user from webui

### ISSUE THREAD

**Issue by T1loc** [openSUSE/open-build-service#695]
With the Admin login, If I add an user with a dot (eg : name.lastame) all actions are unusable (Edit, Delete user for example).

I create the user 
![obs1](https://cloud.githubusercontent.com/assets/7666426/3147125/bd66cabc-ea52-11e3-8dd3-13f0149c3640.png)

When I try to access it
![obs2](https://cloud.githubusercontent.com/assets/7666426/3147126/bd66eb28-ea52-11e3-97c3-4ce97d0a8f1d.png)

OBS server : 2.5 (latest appliance)

**Comment by hennevogel** [comment]
This is fixed

**Comment by c-hoeger** [comment]
bug still seem to exist somehow, see http://lists.opensuse.org/opensuse-buildservice/2015-08/msg00103.html

**Comment by hennevogel** [comment]
Logging in is not exactly what this bug is about. @c-hoeger can you please open a new one? Thanks

**Comment by c-hoeger** [comment]
done https://github.com/openSUSE/open-build-service/issues/1064
